apiVersion: batch/v1
kind: Job
metadata:
  name: youtubehaikubot
spec:
  template:
    metadata:
      name: youtubehaikubot
    spec:
      containers:
      - name: youtubehaikubot
        image: eu.gcr.io/telegram-bots-179510/youtubehaikubot
        imagePullPolicy: Always
        env:
        - name: POSTER_TOKEN
          valueFrom:
            secretKeyRef:
              name: telegram-poster
              key: token
        - name: POSTER_REDIS_HOST
          value: redis
      restartPolicy: OnFailure